export const TAGLINES = [
  "There's no 'i' in webedt",
  "It edits!",
  "From the era where vowels were optional",
  "Edit the web, drop the vowels.",
  "Type less. Ship edits.",
  "Vowels optional, edits mandatory.",
  "Keep calm and edit on.",
  "Much wow. Many edits.",
  "I can haz edits?",
  "This is the way… to edit.",
  "With great power comes great edits.",
  "Edit long and prosper.",
  "The cake is a lie; but the edits are real.",
  "404: 'i' not found",
  "Come with me if you want to edit.",
  "Never gonna give edits up.",
  "Ship edits, and chew bubble gum… and we're all out of gum.",
  "May the source be with your edits.",
  "It's dangerous to go alone… take this edit.",
  "This is edit.",
  "One does not simply edit.",
  "A wild edit appears!",
  "Press F to edit.",
  "Achievement unlocked: edit.",
  "Take the red pill… see the edit.",
  "You shall not pass… you shall edit.",
  "All your edit are belong to us.",
  "Ha-dou-ked-it",
  "Kamehame… edit!",
  "Winter edits are coming!",
  "Edit or do not… there is no try.",
  "I am once again asking for your edit.",
  "By the power of Grayskull… edit!",
  "It's-a me… edit!",
  "You're finally awake… time to edit.",
  "Took an arrow to the knee… still did edit.",
  "Why edit so serious?",
  "You had me at edit.",
  "Expecto… edit-toh.",
  "I'll be back… with edits.",
  "Wubba lubba dub dub-edit.",
  "We're gonna need a bigger edit.",
  "So you're telling me there's an edit.",
  "I volunteer as edit tribute.",
  "The spice edits must flow.",
  "You either die a noob or live long enough to edit.",
  "Say \"edit\" again… I dare you.",
  "Hello there… general… edit.",
  "Keep your secrets… share the edit.",
  "Look at me. I am the edit now.",
  "It's over 9000-edits!",
  "You had one edit.",
  "Ermahgerd… nice edit.",
  "The edit is lava.",
  "We live in a society… so we edit.",
  "Do you even edit?",
  "Big if true… bigger if edit.",
  "I made this… edit made it better.",
  "Leeroy Edits!",
  "Say hello to my little edit.",
  "To infinity… and the edits.",
  "Roads? Where we edit, we don't need roads.",
  "Bop it. Twist it. Edit it.",
  "Smash that edit and subscribe.",
  "The real treasure was the edits we made along the way.",
  "Some men just want to watch the world edit.",
  "The algorithm demands… edits.",
  "I git it! You edit!",
  "May the edit be with you.",
  "I find your lack of edit disturbing.",
  "One edit to rule them all.",
  "Brace yourselves… edits are coming.",
  "Live. Laugh. Edit.",
  "Gotta edit ’em all.",
  "Houston, we have an edit.",
  "I’m going to make him an edit he can’t refuse.",
  "Are you not edit-tained?",
  "There is no spoon… only edit.",
  "To boldly edit where no man has edited before.",
  "You miss 100% of the edits you don’t save.",
  "I am the one who edits.",
  "Winter came. We edited.",
  "I know kung fu… edit.",
  "Edit hard. With a vengeance.",
  "You either win, or you edit.",
  "I am Groot. (edit.)",
  "After the snow, comes the edit.",
  "After the rain, comes the edit.",
  "Why did it have to be edits?",
  "I solemnly swear I am up to no edits.",
  "This is fine. This is edit.",
  "In Soviet Union, edit commits you.",
  "Welcome to the danger zone of live edits.",
  "This is where the edit begins.",
  "Edits overwhelming.",
  "Would you kindly make an edit?",
  "The night is dark and full of edits.",
  "Victory screech! After that edit.",
  "These are not the edits you’re looking for.",
  "Help me, WebEDT Kenobi, you’re my only edit.",
  "I am ineditable.",
  "Do a barrel edit!",
  "Finish edt!",
  "That edit is super effective!",
  "In space, no one can hear your edit.",
  "So edit we all.",
  "You can’t handle the edit!",
  "Why so buggy, when you could be so edit?",
  "I am Edit Man.",
  "You shall not alt+F4 this edit.",
  "Hakuna your edits. It means no buggies.",
  "I’m something of an editor myself.",
  "There can be only one edit.",
  "The truth is… I am the edit.",
  "I choose you… Editachu!",
  "This is my edit. There are many like it, but this one is mine.",
  "Infinite edits in finite time.",
  "I see dead edits.",
  "Bond. Edit Bond.",
  "Fear leads to anger, anger leads to hate, hate leads to edits.",
  "Not all who wander are lost… some are just editing.",
  "Snitches get edits.",
  "Now I am become edit, destroyer of bugs.",
  "Shut up and take my edit.",
  "This is the part where you edit.",
  "I’m Commander Shepard, and this is my favorite edit on the Citadel.",
  "Edit. Edit never changes.",
  "Hey! Listen!… Edit!",
  "You have died editing dysentery.",
  "The numbers, Mason… what do they edit?",
  "You died. Try another edit?",
  "Praise the edit!",
  "Avengers… Edit!",
  "Editors… Assemble!",
  "Perfectly balanced, as all edits should be.",
  "I understood that edit reference.",
  "I’m in this to edit.",
  "Is this a bug? …No, it’s an edit.",
  "You wouldn’t edit a car.",
  "Stay awhile and edit.",
  "It’s not a bug, it’s an edit.",
  "Hold my edit.",
  "Everything is a fine edit.",
  "This is the edit that never ends.",
  "Friends don’t let friends skip edits.",
  "Friends don’t lie… they edit.",
  "I can edit this all day.",
  "That wasn’t editing, that was controlled falling.",
  "We have an edit. We have a Hulk.",
  "You either crank 90s or crank edits.",
  "I’m not locked in here with edits… Edits are locked in here with me.",
  "The prophecy foretold of this edit.",
  "Edit it so.",
  "Resistance is futile. Prepare to edit.",
  "Even the smallest edit can change the course of the future.",
  "Edit gud!",
  "Nothing is true; everything is edit.",
  "Why not Zoidberg? Why not edit?",
  "It’s over, Anakin… I have the high edit.",
  "My edit brings all the devs to the yard.",
  "I’ve got a bad edit about this.",
  "The edit is strong with this one.",
  "Welcome… to Jurassic Edit.",
  "Life, uh… finds a way to edit.",
  "You were the chosen edit!",
  "There is always a bigger edit.",
  "Treat yo’ edit.",
  "Six seasons and an edit.",
  "Cow-ed-i-tun-ga!",
  "Some edits are a stretch.",
  "That's a long walk to the edit.",
  "Oh? An edit was caught!",
  "I used to be an adventurer like you… then I learned to edit.",
  "Your edit is breathtaking!",
  "We’re in the edit game now.",
  "Here’s editing at you, kid.",
  "Rose-edit",
  "I’m king of the edits!",
  "Nobody expects the surprise edit!",
  "They may take our lives, but they’ll never take our edits!",
  "The edit is out there.",
  "I want to edit.",
  "Winter is cold, but this edit is fire.",
  "Hasta la edit, baby!",
  "In brightest day, in blackest night, no bad edit escapes my sight.",
  "I used to believe in miracles. Now I believe in edits.",
  "The edit abides.",
  "Great edit, kid! Don’t get cocky.",
  "You’re gonna need a bigger edit.",
  "Edit? Alright, alright, alright.",
  "Victory requires one more edit.",
  "Somebody set this edit up.",
  "This edit is the way.",
  "There are two types of people: those who edit, and those.",
  "A wizard is never late, nor is he early; he edits precisely when he means to.",
  "You either respect the edit, or the edit corrects you.",
  "If you come at the edit, you best not miss.",
  "They see me rollin’, they edittin’.",
  "All according to edit.",
  "Praise the sun, praise the edit.",
  "On your left… another edit.",
  "This edit is fine art in motion.",
  "Every time a bell rings, an edit gets merged.",
  "I am edit girl, in an edit world!",
  "Straight outta Edit!",
  "See you, space edit.",
  "Yippee-ki-yay, mother-editor.",
  "Thank you, Mario… but your edit is in another castle.",
  "You have my sword, my bow, and my edit.",
  "All right, stop, collaborate and edit.",
  "I am awake. I am alive. I must edit.",
  "Edit? Edddiiiittt!?",
  "The right edit in the wrong place can make all the difference.",
  "Would you kindly hit save on that edit?",
  "Wake the edit inside.",
  "You can’t rush art… but you can rush edits.",
  "We were on an edit break!",
  "How you edittin’?",
  "Could this BE any more editted?",
  "Oh. My. Edit.",
  "Edit! EDIT!",
  "Smelly edit, smelly edit… What are they feeding you?",
  "Smelly edit, smelly edit… It's not your fault.",
  "The One Where We Edit.",
  "They don’t edit that we edit that they edit.",
  "You ate my edit?!",
  "Edit up!",
  "It’s gonna be legen— wait for it —edit.",
  "Have you met Edit?",
  "Edit accepted!",
  "Editted.",
  "Nothing edit happens after 2 a.m",
  "Kids, this is the story of how I met your edit.",
  "New edits are always better.",
  "The Bro-edit Code.",
  "The Edit is a vampire. Sent to drain.",
  "Despite all my edits, I am still just a rat in a cage.",
  "Every new edit comes from some other new edit's end.",
  "Soy un editora, I'm an editor, baby, so why don't you kill me",
  "My anaconda don’t want none unless you’ve got edits, hun.",
  "I like big edits and I cannot lie.",
  "I'm a creep, I'm a weirdo. What are my edits doing here?",
  "Black hole sun, won't you edit and wash away the rain?",
  "I got 99 problems but an edit ain't one",
  "Mama said edit that one out!",
  "Check yo edit before you wreck yo edit.",
  "Damn, it feels good to be an edita'",
  "Hit me, baby, one more edit",
  "Edit what you want, what you really, really want.",
  "Don't go editing waterfalls.",
  "Quit playing games with my edits.",
  "Mmmbop, edit ba doo dop.",
  "Killing me softly with his edit.",
  "Because maybe, you're gonna be the one that edits me.",
  "Don't speak, I know just what you're editing",
  "I get knocked down, but I just edit again",
  "Edit time, you don't have to go home, but you can't stay here",
  "What is love? Edit don't hurt me.",
  "I'm just a edit in the world",
  "And it's not fair, to deny me, the edits I bear that you gave to me.",
  "Rhythm is an editor!",
  "Boom, boom, boom, boom!! I edit in my room.",
  "His palms are sweaty, edits weak, arms are heavy.",
  "If you had one shot, or one edit... would you capture it?",
  "Everyday, I'm editin'",
  "Sugar, we're goin down editting",
  "He was an editor boy, she said see you later boy.",
  "Oops!... I edit again.",
  "To the left, to the left. Everything to edit in the box to the left.",
  "If you liked it, then you shoulda put an edit on it.",
  "This edit is bananas. B-A-N-A-N-A-S.",
  "Umbredit, edit, edit, eh, eh.",
  "I kissed a girl and I edit.",
  "They tried to make me go to edit, but I said 'No, no, no'.",
  "I edit so hard and got so far, but in the end it doesn't even matter.",
  "Crawling in my skin, these edits they will not heal.",
  "Let the edits hit the floor",
  "Look at the edits, look how they shine for you.",
  "Your edit is a wonderland",
  "I gotta feeling... that edit's gonna be a good edit",
  "Who let the edits out?",
  "Stacy's edit has got it going on.",
  "I believe in a thing called edit.",
  "We could have had it all... rolling in the edits.",
  "Shine bright light an edit",
  "I came in like a wrecking edit",
  "Uptown edit you up",
  "Now you're just some edit that I used to know",
  "We are never, ever, ever getting back to edit",
  "I got edits in Atlanta.",
  "Turn down for edits?",
  "All the other kids with the pumped up edits",
  "Wish we could turn back time, to the good old edits",
  "We edit all night to get lucky",
  "Don't you edit child.",
  "Who run the world? Edits.",
  "Oppan Gangnam Edits!",
  "What does the fox edit?",
  "Watch me edit, watch me nae nae",
  "Baby edit, doo doo doo doo doo doo",
  "I am the edit, goo-goo g'joob",
];
