export const TAGLINES = [
  "There's no 'i' in webedt",
  "It edits!",
  "From the era where vowels were optional",
  "Edit the web, drop the vowels.",
  "Type less. Ship edits.",
  "Vowels optional, edits mandatory.",
  "Keep calm and edit on.",
  "Much wow. Many edits.",
  "I can haz edits?",
  "This is the way... to edit.",
  "With great power comes great edits.",
  "Edit long and prosper.",
  "The cake is a lie; but the edits are real.",
  "404: 'i' not found",
  "Come with me if you want to edit.",
  "Never gonna give edits up.",
  "Ship edits, and chew bubble gum—and we're all out of gum.",
  "May the source be with your edits.",
  "It's dangerous to go alone—take this edit.",
  "This is edit.",
  "One does not simply skip edit.",
  "A wild edit appears!",
  "Press F to edit.",
  "Achievement unlocked: edit.",
  "Take the red pill—see the edit.",
  "You shall not pass—you shall edit.",
  "All your edit are belong to us.",
  "Ha-dou-ked-it",
  "Kamehame… edit!",
  "Winter is coming—do the edit.",
  "Edit or do not—there is no try.",
  "I am once again asking for your edit.",
  "By the power of Grayskull—edit!",
  "It's-a me… edit!",
  "You're finally awake—time to edit.",
  "Took an arrow to the knee—still did edit.",
  "Why so serious? Do edit.",
  "You had me at edit.",
  "Expecto… edit-toh.",
  "I'll be back—with edits.",
  "Wubba lubba dub dub—edit.",
  "We're gonna need a bigger edit.",
  "So you're telling me there's a chance… for edit.",
  "I volunteer as tribute… to edit.",
  "The spice must flow—edit must grow.",
  "You either die a noob or live long enough to edit.",
  "Say \"edit\" again—I dare you.",
  "Hello there—general… edit.",
  "Keep your secrets—share the edit.",
  "Look at me. I am the edit now.",
  "It's over 9000—edits!",
  "You had one job: edit.",
  "Ermahgerd—nice edit.",
  "The floor is lava—jump to edit.",
  "We live in a society—so we edit.",
  "Do you even edit?",
  "Big if true—bigger if edit.",
  "I made this—edit made it better.",
  "Leeroy Jedits!",
  "Say hello to my little edit.",
  "To infinity—and b-edits.",
  "Roads? Where we're editting, we don't need roads.",
  "Bop it. Twist it. Edit it.",
  "Smash that edit and subscribe.",
  "The real treasure was the edits we made along the way.",
  "Some men just want to watch the world edit.",
  "The algorithm demands… edits."
];
