version: '3.8'

services:
  github-worker:
    image: dockerregistry.etdofresh.com/github-worker:latest
    ports:
      - target: 5002
        published: 5003
        protocol: tcp
        mode: ingress
    environment:
      - PORT=5002
      - TMP_DIR=/tmp
      - STORAGE_WORKER_URL=${STORAGE_WORKER_URL:-}
    deploy:
      replicas: 5
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
