version: '3.8'

services:
  ai-coding-worker:
    image: dockerregistry.etdofresh.com/ai-coding-worker:latest
    ports:
      - target: 5000
        published: 5001
        protocol: tcp
        mode: ingress
    environment:
      - PORT=5000
      - TMP_DIR=/tmp
      - STORAGE_WORKER_URL=${STORAGE_WORKER_URL:-}
      - DB_BASE_URL=${DB_BASE_URL:-}
    deploy:
      replicas: 10
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
